# Generated by Django 5.0 on 2023-12-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeOffencesCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(verbose_name='номер статьи')),
                ('text', models.TextField(verbose_name='текст')),
                ('notification', models.BooleanField(blank=True, null=True, verbose_name='предупреждение')),
                ('conjunction_1', models.CharField(blank=True, choices=[('OR', 'Или'), ('AND', 'И')], max_length=3, null=True, verbose_name='союз')),
                ('penalty', models.CharField(blank=True, max_length=20, null=True, verbose_name='сумма штрафа')),
                ('conjunction_2', models.CharField(blank=True, choices=[('OR', 'Или'), ('AND', 'И')], max_length=3, null=True, verbose_name='союз')),
                ('deprivation_driver_license', models.CharField(blank=True, max_length=20, null=True, verbose_name='срок лишение ВУ')),
                ('conjunction_3', models.CharField(blank=True, choices=[('OR', 'Или'), ('AND', 'И')], max_length=3, null=True, verbose_name='союз')),
                ('arrest', models.CharField(blank=True, max_length=20, null=True, verbose_name='срок ареста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
            ],
        ),
    ]
