# Generated by Django 5.0 on 2023-12-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_administrativeoffencescodechapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeoffencescodechapter',
            name='number',
            field=models.SmallIntegerField(verbose_name='номер главы'),
        ),
    ]
