# Generated by Django 5.0 on 2023-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0006_alter_administrativeoffencescode_deprivation_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeoffencescode',
            name='number',
            field=models.FloatField(verbose_name='номер статьи'),
        ),
    ]
