# Generated by Django 5.0 on 2023-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0009_rename_conjunction_2_criminalcode_conjunction'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalcode',
            name='compensation',
            field=models.BooleanField(blank=True, null=True, verbose_name='возмещение ущерба'),
        ),
        migrations.AddField(
            model_name='criminalcode',
            name='conjunction_2',
            field=models.CharField(blank=True, choices=[('OR', 'или'), ('AND', 'и')], max_length=3, null=True, verbose_name='союз'),
        ),
    ]
